# Generated by Django 3.2.16 on 2025-12-22 17:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20251222_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 12, 22, 17, 55, 53, 199031, tzinfo=utc), verbose_name='Создано'),
            preserve_default=False,
        ),
    ]
